### ISSUE TITLE
user settings example

### ISSUE THREAD

**Issue by AliveDD** [brockriemenschneider/REM-PX#1]
> The default size of 1rem is 16px which can be changed in the user settings.

where i can get user settings example for change default size?

**Comment by brockriemenschneider** [comment]
https://github.com/BsWiM/REM-PX/blob/master/REM-PX.sublime-settings

**Comment by AliveDD** [comment]
After install package with package control — by default all [REM-PX setting files are empty (screenshot)](http://imgbox.com/sPrw2mnT).
But if copy this code in user REM-PX.sublime-settings, plugin are work correctly.
Thank u, god bless
